name: Deploy Backend

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Run tests
      run: |
        cd backend
        npm test
      continue-on-error: true

    - name: Build application
      run: |
        cd backend
        npm run build 2>/dev/null || echo "No build script found"

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # Navigate to project directory
          cd ${{ secrets.PROJECT_PATH }}

          # Backup current .env
          cp .env .env.backup.$(date +%Y%m%d_%H%M%S)

          # Pull latest changes
          git pull origin main

          # Install dependencies
          npm ci --production

          # Restart service
          pm2 restart ecosystem.config.js
          pm2 save

          # Health check
          sleep 10
          if curl -f https://matrix-api.oldantique50.com/api/health; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Health check failed!"
            exit 1
          fi

    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: "Backend deployment failed"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
